blog/urls.py
from django.urls import path
from . import views

urlpatterns = [  # IP주소/blog/
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page), # IP주소/blog/category/slug/
    path('tag/<str:slug>/', views.tag_page),    # IP주소/blog/tag/slug/
    path('search/<str:q>/', views.PostSearch.as_view())

    #path('', views.index), #  IP주소/blog/
    #path('<int:pk>/', views.single_post_page)
]

myDjangoPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ # IP주소/
    path('admin/', admin.site.urls), #ip주소/admin/
    path('blog/', include('blog.urls')), # IP주소/blog/
    path('', include('single_pages.urls')), # IP주소/
    path('accounts/', include('allauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def _get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    #%Y 2022, %y 22
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 추후 author 작성
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag,  blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}::{self.author} :  {self.created_at}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]  # a.txt => a txt

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return "https://dummyimage.com/50x50/ced4da/6c757d.jpg"

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return "https://dummyimage.com/50x50/ced4da/6c757d.jpg"

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category'] # , 'tags'
    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate,self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tag_list = tags_str.split(';')
            for t in tag_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tag_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    # 모델명_form.html

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';')
                tag_list = tags_str.split(';')
                for t in tag_list :
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostCreate, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context


class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context
    # 템플릿은 모델명_list.html : post_list.html
    # 매개변수 모델명_list : post_list

class PostSearch(PostList):  # ListView 상속, post_list, post_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        return context

    # 템플릿은 모델명_detail.html : post_detail.html
    # 매개변수 모델명 : post
def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post,pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else: # GET
            return redirect(post.get_absolute_url())
    else: # 로그인 안한 사용자
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin,UpdateView):
    model = Comment
    form_class = CommentForm
    # 템플릿 : comment_form


    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def category_page(request,slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request,'blog/post_list.html', {
        'category' : category,
        'post_list' : post_list,
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(request, 'blog/post_list.html', {
        'tag': tag,
        'post_list' : post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })


#def index(request):
 #   posts = Post.objects.all().order_by('-pk')
  #  return render(request, 'blog/index.html', {'posts':posts})

#def single_post_page(request,pk):
 #   post1 = Post.objects.get(pk=pk)
  #  return render(request, 'blog/single_post_page.html',{'post':post1})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}Blog{% endblock %}</title>
  <link href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen" ></link>
  <script src="https://kit.fontawesome.com/38c1ac657f.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'blog/navbar.html' %}

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area">
        {% block main_area %}
        {% endblock %}
      </div>
      <div class="col-md-4 col-lg-3">
        {% include 'blog/sidebar.html' %}
      </div>
    </div>
  </div>

  {% include 'blog/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

            {{form | crispy}}

        <button type="submit" class="btn-primary float-right">Submiit</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
  <!-- Footer-->
  <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Internet Programming 2022</p>
    </div>
  </footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    {% for p in posts %}
        <h2><a href="{{p.get_absolute_url}}"> {{ p.title}}</a></h2>
        <h3>{{ p.created_at }}</h3>
        <p> {{ p.content }}</p>
    {% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">Internet Programming</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about_me/">About me</a>
          </li>
          </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.socialaccount_set.all.0.get_avatar_url %}
              <img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" width="25px" />
              {% else %}
              <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px" />
              {% endif %}
              {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
            </div>
            </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> LogIn</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-6">
              <a role="button" class="btn btn-outline-dark btn-block btn-sm"
              href="{% provider_login_url 'google' %}">
                <i class="fa-brands fa-google"></i> LogIn with google
              </a>
              <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                href="/accounts/login/">
                <i class="fa-regular fa-envelope"></i> LogIn with Email
              </a>
            </div>
            <div class="col-6">
              <a role="button" class="btn btn-outline-dark btn-block btn-sm"
              href="/accounts/signup/">
                <i class="fa-regular fa-envelope"></i> SignUp with Email
              </a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{post.title}} - Blog
{% endblock %}

{% block main_area %}

                    <!-- Post content-->
                    <div id="post-area">
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title | lower }}</h1>
                            {% if post.hook_text %}
                            <h5 class="text-muted">{{post.hook_text}} </h5>
                            {% endif %}
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">
                                Posted on {{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author|upper}}
                            </div>
                            <!-- Post categories-->
                            {% if post.category %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="{{post.category.get_absolute_url}}">
                                {{post.category}}
                            </a>
                            {% else %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="/blog/category/no_category">
                                미분류
                            </a>
                            {% endif %}

                        </header>
                        {% if user.is_authenticated and user == post.author %}
                            <a class="btn btn-info float-right" href="/blog/update_post/{{post.pk}}/" role="button">
                                <i class="fas fa-pen"> Edit Post</i>
                            </a>
                        {% endif %}
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                            {% if post.head_image %}
                            <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{post.title}}의 head_image" />
                            {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image" />
                            {% endif %}
                        </figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{post.content}}</p>
                            {% if post.tags.exists %}
                                <i class ="fas fa-tag"></i>
                                {% for t in post.tags.iterator %}
                                    <span class="badge badge-pill badge-light">
                                        <a href="{{t.get_absolute_url}}">
                                            {{t}}
                                        </a>
                                    </span>
                                {% endfor %}
                             {% endif %}
                             <br><br>
                            {% if post.file_upload %}
                            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                                {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fa-regular fa-file-excel"></i>
                                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc'%}
                                <i class="fa-regular fa-file-word"></i>
                                {% else %}
                                <i class="fa-regular fa-file"></i>
                                {% endif %}
                                Download {{post.get_file_name}}
                            </a>
                            {% endif %}
                        </section>
                    </div>
                    <!-- Comments section-->
                    <div id="commenet-area" class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                    {% if user.is_authenticated %}
                                    <form class="mb-4" id="comment-form" method="post" action="{{post.get_absolute_url}}new_comment/">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{comment_form | crispy}}
                                        </div>
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </form>
                                    {% else %}
                                        <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                                        data-toggle="modal" data-target="#loginModal">
                                            Log in and Leave a comment
                                        </a>
                                    {% endif %}
                                </form>
                                {% if post.comment_set.exists %}
                                {% for comment in post.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">
                                   <img class="rounded-circle mr-3" src="{{comment.get_avatar_url}}" alt="{{comment.author}} "width=60px />
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and  comment.author == user %}
                                            <a role="button" class="btn btn-sm btn-info float-right"
                                               href="/blog/update_comment/{{comment.pk}}/">
                                                Edit
                                            </a>
                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text_muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks}}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create a Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Create a new Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form | crispy}}
              <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" class="textInput textInput form-control">
              </div>
        </table>
        <button type="submit" class="btn-primary float-right">Submiit</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}
        {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff %}
                <a class="btn btn-info float-right" href="/blog/create_post/" role="button">
                    <i class="fas fa-pen"> New Post</i>
                </a>
            {% endif %}
        {% endif %}
        <h2>Blog
            {% if search_info %}
            <span class="badge badge-secondary ">{{search_info}}</span>
            {% endif %}
            {% if category %}
             - <span class="badge badge-secondary ">{{category}}</span>
            {% endif %}
            {% if tag %}
            - <i class ="fas fa-tag"></i>
            <span class="badge badge-secondary ">
                {{tag}} ({{tag.post_set.count}})
            </span>
            {% endif %}
        </h2>
        {% if post_list.exists %}
        {% for p in post_list %}
        <div class="card mb-4" id="post-{{p.pk}}">
          {% if p.head_image %}
          <img class="card-img-top" src="{{p.head_image.url}}" alt="{{p}}의 head_image" />
          {% else %}
          <img class="card-img-top" src="https://picsum.photos/seed/{{p.pk}}/800/200" alt="random image" />
          {% endif %}
          <div class="card-body">
            {% if p.category %}
              <span class="badge badge-secondary float-right">
                  <a href="{{p.category.get_absolute_url}}">
                      {{p.category}}
                  </a>
              </span>
            {% else %}
              <span class="badge badge-secondary float-right">
                  <a href="/blog/category/no_category/">
                      미분류
                  </a>
              </span>
            {% endif %}
            <h2 class="card-title">{{p.title | upper}}</h2>
            {% if p.hook_text %}
            <h5 class="text-muted"> {{p.hook_text}}</h5>
            {% endif %}
            <p class="card-text">{{p.content | truncatechars:100 }}</p>
            {% if p.tags.exists %}
              <i class ="fas fa-tag"></i>
              {% for t in p.tags.iterator %}
              <span class="badge badge-pill badge-light">
                  <a href="{{t.get_absolute_url}}">
                      {{t}}
                  </a>
              </span>
              {% endfor %}
            {% endif %}
              <br><br>
            <a class="btn btn-primary" href="{{p.get_absolute_url}}">Read more →</a>
          </div>
          <div class="card-footer">
            <div class="small text-muted">{{p.created_at | date:"Y-m-d h:m:s"}}</div>
            <a href="#">{{p.author | upper}}</a>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>아직 게시물이 없습니다.</h5>
        {% endif %}

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Pagination">
          <hr class="my-0" />
          <ul class="pagination justify-content-center my-4">
            {% if page_obj.has_previous %}
            <li class="page-item "><a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Older</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#!">Older</a></li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Update a new Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" value="{{tags_str_dafault}}"
                    class="textInput textInput form-control">
            </div>

        <button type="submit" class="btn-primary float-right">Submiit</button>
    </form>
{% endblock %}

blog/templates/blog/sidebar.html
        <!-- Search widget-->
        <div class="card mb-4">
          <div class="card-header"><i class="fa-solid fa-magnifying-glass"></i> Search</div>
          <div class="card-body">
            <div class="input-group">
              <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
              <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
            </div>
          </div>
        </div>
        <script>
            function searchPost(){
                let searchValue = document.getElementById('search-input').value.trim();
                if(searchValue.length > 1){
                    location.href = "/blog/search/" + searchValue +"/"
                }
                else{
                    alert('검색어('+ searchValue+')가 너무 짧아요');
                }
            };
            document.getElementById('search-input').addEventListener('keyup', function(event){
                if (event.key === 'Enter'){
                    searchPost();
                }
            });
        </script>
        <!-- Categories widget-->
        <div class="card mb-4" id='category_card'>
          <div class="card-header">Categories</div>
          <div class="card-body">
            <div class="row">

                <ul class="list-unstyled mb-0">
                  {% for c in categories %}
                  <li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
                  {% endfor %}
                  <li><a href="/blog/category/no_category/">미분류 ({{no_category_post_count}})</a></li>
                </ul>


            </div>
          </div>
        </div>

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <h4>{{post.created_at}}</h4>
    <p>{{post.content}}</p>

    <hr />
    <h3>여기에 댓글을 출력하면 되겠죠?</h3>
</body>
</html>